services:
  - type: web
    name: whatsapp-ultimate-agent
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 127.0.0.1 --port $PORT
